// Code generated by goctl. DO NOT EDIT.

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	usersFieldNames          = builder.RawFieldNames(&Users{})
	usersRows                = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet   = strings.Join(stringx.Remove(usersFieldNames, "`account_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	usersRowsWithPlaceHolder = strings.Join(stringx.Remove(usersFieldNames, "`account_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *Users) (sql.Result, error)
		FindOne(ctx context.Context, accountId int64) (*Users, error)
		FindOneByAccount(ctx context.Context, account string) (*Users, error)
		FindOneByUserName(ctx context.Context, userName string) (*Users, error)
		Update(ctx context.Context, data *Users) error
		Delete(ctx context.Context, accountId int64) error
	}

	defaultUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Users struct {
		AccountId  int64     `db:"account_id"`
		Account    string    `db:"account"`
		UserName   string    `db:"user_name"`
		PwdHash    string    `db:"pwd_hash"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		Status     int64     `db:"status"` // 0: not-in-use, 1: not-active, 2: in-use, 3: black-list
		RoleBitmap int64     `db:"role_bitmap"`
	}
)

func newUsersModel(conn sqlx.SqlConn) *defaultUsersModel {
	return &defaultUsersModel{
		conn:  conn,
		table: "`users`",
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, accountId int64) error {
	query := fmt.Sprintf("delete from %s where `account_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, accountId)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, accountId int64) (*Users, error) {
	query := fmt.Sprintf("select %s from %s where `account_id` = ? limit 1", usersRows, m.table)
	var resp Users
	err := m.conn.QueryRowCtx(ctx, &resp, query, accountId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByAccount(ctx context.Context, account string) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where `account` = ? limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, account)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByUserName(ctx context.Context, userName string) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where `user_name` = ? limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, usersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Account, data.UserName, data.PwdHash, data.Status, data.RoleBitmap)
	return ret, err
}

func (m *defaultUsersModel) Update(ctx context.Context, newData *Users) error {
	query := fmt.Sprintf("update %s set %s where `account_id` = ?", m.table, usersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Account, newData.UserName, newData.PwdHash, newData.Status, newData.RoleBitmap, newData.AccountId)
	return err
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}
