// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Account  string `form:"account"`
	Password string `form:"password"`
	TraceId  string `header:"Trace-Id"`
}

type LoginResponse struct {
	AccessToken string `json:"access_token"`
	UserName    string `json:"user_name"`
	Uuid        string `json:"uuid"`
}

type RegisterRequest struct {
	Account  string `form:"account"`
	Password string `form:"password"`
	Username string `form:"username"`
	TraceId  string `header:"Trace-Id"`
}

type RegisterResponse struct {
	Message string
}
