// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	auth "kapibara-apigateway-gozero/restful/auth/internal/handler/auth"
	"kapibara-apigateway-gozero/restful/auth/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth/v1"),
		rest.WithTimeout(60000*time.Millisecond),
	)
}
